DROP TABLE IF EXISTS users_threads;
DROP TABLE IF EXISTS users_groups;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS threads;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS groups;

